---
title: "Excursion"
---

*Note that this excursion will be adapted to the situation of the Sundhnjúkagígar system. An eruption has been predicted for a while and might be overdue. We assume it will continue to be possible to explore Reykjanesskagi.* 

*Check out the news and alerts about the [volcanic activity](https://en.vedur.is/volcanoes/fagradalsfjall-eruption/news-and-alerts/) as well as the news about recent [earthquakes](https://en.vedur.is/earthquakes-and-volcanism/earthquakes/reykjanespeninsula/) in the Reykjanes peninsula.*

**Price for the excursion will be 5.000 ISK (close to 35 euros) per participant, to cover bus and some light refreshments.
_Payment will be done on the last day_**

Please register here: [Excursion registration](https://docs.google.com/spreadsheets/d/177RuPA6R0SAqunHhq-K_S-ESJspCo675uuDHbYBn3rM/edit?usp=sharing)



## Agenda for an excursion

Our guide will be Kristinn Arnar Guðjónsson, an expert in the geology of Reykjanes. Kristinn has revised the excursion plan as follows (ie we have decided against a trek to Nátthagi):

### WGFAST Excursion - Reykjanes peninsula 12 April 2025

Volcanic site close to Grindavík, MFRI Aquaculture and other wonders of Reykjanes

- **12.40: Departure Fosshótel Reykjavik**

- **13.00: Departure Viking Hotel Hafnarfjordur**

- 13:30 Photo opportunity at lake Kleifarvatn

- 13:30–35 Seltún (the geysirs of Krísuvík).

- 14:00 Arrive in Grindavík, a small fishing village on the south shore of Reykjanes peninsula. Explore the damage to infrastructure and open fissures after series of earthquakes in recent years.

- 14:40 Explore the defence barriers around Grindavík and the geothermal power plant. Get a view of the new lava and the volcanic craters.

- 16:00: Drive to the MFRI Aquaculture facility at Staður (‘Place’) with sightseeing and refreshments.

- 17:00 Onwards further west to Reykjanes — Gunnuhver - hot springs and the Toe of Reykjanes, continental divide and after that back to Reykjavík.

- **19:30/20.00:  Arrival in Hafnarfjörður and Reykjavík.**
